### ISSUE TITLE
GUI Bug: Tab converter window is to big.

### ISSUE THREAD

**Issue by Martin-Brejniak** [mike-jshen/2311-Project#12]
**ID:** 12

**Author:** Martin Brejniak.
**Contact Info:** martin.brejniak@bell.net

**Version:** March, 21/2021 Version of Software.
**Platform:** Windows 10. Eclipse 4.18.0. JavaSE-13. Acer Swift 1 Laptop (_Screen Size:_ 14 inch).

**Reproduction:** I simply booted up the software, and clicked on the "Launch Program" button on the start-up window.
**Expected:** I expected the tab converter window to fit on my screen so I could clearly see all the options I could do.
**Actual:** The window was too big, hiding the 4 buttons at the bottom of the window, and part of the top (See image).

**Priority:** Low.
**Severity:** Some people might not notice the stuff at the bottom, and/or not know how to manually fix it. It affects user-friendliness, so try to have it fixed by the final release.

<img width="960" alt="Capture " src="https://user-images.githubusercontent.com/77299294/112235079-4f252100-8c14-11eb-97c9-0e417bf2ee13.PNG">

**Comment by aman9824** [comment]
Fixed
