### ISSUE TITLE
Doesn't work with other tabs 

### ISSUE THREAD

**Issue by Nobaiha** [mike-jshen/2311-Project#13]
ID# 13
Who Raised: Nobaiha Zaman Rayta
Title: Doesn't work with other tabs
Version: Prototype - 72ccfc9b8efb8eabb8d5383454318f39bd0b8a50
Platform: Windows 10
Reproduction: 1. Open the application
2. Input a text tab
3. Convert and save tab
Expected Outcome: To work with other tabs other than those provided
Actual Outcome: Doesn't work with other tabs.
Priority: High
Severity: High
Screenshots: 
![image](https://user-images.githubusercontent.com/77299896/112240495-d11a4780-8c1e-11eb-84fa-8e055fd43f00.png)
![image](https://user-images.githubusercontent.com/77299896/112240550-e98a6200-8c1e-11eb-9740-e5fd935bd6ac.png)
![image](https://user-images.githubusercontent.com/77299896/112240616-01fa7c80-8c1f-11eb-85fd-823d8dd8a831.png)

**Comment by aman9824** [comment]
If you have read our User Manual, At this moment our Notes work only till 9, they don't work for double-digit but will consider it and fix it by this week.
