### ISSUE TITLE
Doesn't convert files selected from directory

### ISSUE THREAD

**Issue by Nobaiha** [mike-jshen/2311-Project#14]
ID# 14
Who Raised: Nobaiha Zaman Rayta
Title: Doesn't convert files selected from directory 
Version: Prototype - 72ccfc9
Platform: Windows 10
Reproduction: 1. Open the application
2. Input a text tab
3. Convert and save tab
Expected Outcome: When a tab is added through the "Add Song" button, the software should convert it to a MusicXML file
Actual Outcome: Added song doesn't convert to expected XML file
Priority: High
Severity: High
Screenshots:
![g11](https://user-images.githubusercontent.com/77299896/112242153-a7165480-8c21-11eb-833d-9de6a8bdfeac.PNG)

Console shows:
![image](https://user-images.githubusercontent.com/77299896/112242079-85b56880-8c21-11eb-8efe-921b01f9b9f0.png)

**Comment by aman9824** [comment]
Sir, I think you haven't read the instructions clearly, You have to view the tab and then click on the convert tab button. It's not an error.
