### ISSUE TITLE
Error Detection Bug: Deleting the last "|" does not cause error.

### ISSUE THREAD

**Issue by Martin-Brejniak** [mike-jshen/2311-Project#15]
**ID:** 15

**Author:** Martin Brejniak.
**Contact Info:** martin.brejniak@bell.net

**Version:** March, 17/2021 Version of Software.
**Platform:** Windows 10. Eclipse 4.18.0. JavaSE-13.

**Reproduction:** I pasted [this tab](https://wiki.eecs.yorku.ca/course_archive/2020-21/W/2311/_media/exampleemajor.txt) into the text window. I then deleted the last "|" on the third row and clicked the "Convert" button.
**Expected:** I expected to not receive the, "_Conversion complete_" message, as deleting the first and middle "|" of the third line results in the tab not being converted.
**Actual:** The tab conversion was successful.

**Priority:** Medium.
**Severity:** With the fantastic error detecting system of the software, a user could become reliant on it. If the user makes a mistake like this, and it doesn't return an error, the user could end up using an incorrect MusicXML. Try to have this fixed by the final release.

_The tab with the last "|" on the third row deleted._
<img width="860" alt="Capture" src="https://user-images.githubusercontent.com/77299294/112242808-ebeebb00-8c22-11eb-8b66-1e9ce705cf8d.PNG">
_The system notifing me the the convertion was successful._
<img width="856" alt="Capture 2" src="https://user-images.githubusercontent.com/77299294/112242837-f27d3280-8c22-11eb-8622-2ff09598a9eb.PNG">
_The tab with the first "|" on the third row deleted. Does not convert successfully._
<img width="856" alt="Capture 3" src="https://user-images.githubusercontent.com/77299294/112242969-1e98b380-8c23-11eb-9715-dc016d2f479e.PNG">

**Comment by aman9824** [comment]
That's, the feature we have, It is more robust, if you extra space or any other things, It will neglect it and work fine
