### ISSUE TITLE
GUI Bug: Save button doesn't work

### ISSUE THREAD

**Issue by Nobaiha** [mike-jshen/2311-Project#16]
ID# 16
Who Raised: Nobaiha Zaman Rayta
Title: Save button doesn't work
Version: Prototype - 72ccfc9
Platform: Windows 10
Reproduction: 1. Open the application
2. Input a text tab
3. Convert and save tab
Expected Outcome: After adding the song when view button is pressed, the tab to be shown.  
Actual Outcome: Doesn't show the tab. 
Priority: low
Severity: low
Screenshots:
![image](https://user-images.githubusercontent.com/77299896/112243336-c6ae7c80-8c23-11eb-9973-a4bce1f4b272.png)

and the console shows : 
![image](https://user-images.githubusercontent.com/77299896/112243392-d928b600-8c23-11eb-8dfc-98a9497a1772.png)

**Comment by aman9824** [comment]
Hello Nobaiha Zaman Rayta,
As you have read in the console, that no file selected means that you have to select the file on the left side of the Tab and then click on the view button then contents would be shown.
