### ISSUE TITLE
Error Detection Bug: Adding a "-" on any line below the first line does not cause error.

### ISSUE THREAD

**Issue by Martin-Brejniak** [mike-jshen/2311-Project#17]
**ID:** 17

**Author:** Martin Brejniak.
**Contact Info:** martin.brejniak@bell.net

**Version:** March, 17/2021 Version of Software.
**Platform:** Windows 10. Eclipse 4.18.0. JavaSE-13.

**Reproduction:** I pasted [this tab](https://wiki.eecs.yorku.ca/course_archive/2020-21/W/2311/_media/exampleemajor.txt) into the text window. I then add a "-" on the left side of the middle "|" on the second row.
**Expected:**  I expected to not receive the, "_Conversion complete_" message, as adding an extra "-"  on the left side of the middle "|" on the first row results in the tab not being converted.
**Actual:** The conversion was successful.

**Priority:** Medium.
**Severity:** With the fantastic error detecting system of the software, a user could become reliant on it. If the user makes a mistake like this, and it doesn't return an error, the user could end up using an incorrect MusicXML. It also states in the user manual that this is an example of an invalid tab (Page 9). Try to have this fixed by the final release.

_The tab with an extra "-" added on the left side of the middle "|" on the second row. Converts successfully._
<img width="862" alt="Capture 2" src="https://user-images.githubusercontent.com/77299294/112243931-d5496380-8c24-11eb-8d25-4ee89d3ac199.PNG">
_The tab with an extra "-" added on the left side middle "|" on the first row. Does not convert successfully._
<img width="854" alt="Capture" src="https://user-images.githubusercontent.com/77299294/112243999-f0b46e80-8c24-11eb-828f-a89df32fa43f.PNG">

**Comment by aman9824** [comment]
That's, the feature we have, It is more robust, if you extra space or any other things, It will neglect it and work fine
