### ISSUE TITLE
Wrong Note Duration

### ISSUE THREAD

**Issue by dokdek** [mike-jshen/2311-Project#18]
**Title:**
Wrong Note Duration

**Reported By:**
Patchanon Suepai

**Version:**
Commit: 72ccfc9

**Platform:**
Windows 10
Java 15
Eclipse 4.18

**Reproduction:**

Open the program as indicated in the user manual. Attempt to paste a tab into the text box, pasting this tab:

|-5--------|
|-5--------|
|-5--------|
|-5--------|
|-5--------|
|-5--------|

Hitting convert, then save, then opening the saved XML file in https://www.soundslice.com/ XML reader.

**Expected:**

The notes should be whole notes, since it is a single note in a measure.

**Actual:**

The notes provided are half notes.

**Priority:**
Low

**Severity:**
Medium

**Screenshots:**

Input Tab:
https://i.imgur.com/FoBRLJP.png

Output Given:
https://i.imgur.com/gkFPHRo.png

**Comment by aman9824** [comment]
Issue Fixed
