### ISSUE TITLE
Files with repeats not creating output file

### ISSUE THREAD

**Issue by gilmore35** [mike-jshen/2311-Project#19]
**ID# 6**

**Who raised it:** Abhirami Venugopal, abhirami@my.yorku.ca

**Version:** March 23,2021 version of software

**Platform:** Windows 10, Eclipse version 4.8.0, JavaSE-15

**Reproduction:**  
1.Open application
2.Press "Add Song" and select [guitar_tab_repeat.txt](https://github.com/mike-jshen/2311-Project/files/6196229/guitar_tab_repeat.txt)
3.Press "Convert"
4.Press "Save"

**Expected:** I expected the app to show “>> Conversion complete” and to be able to download a MusicXML file.  I expected a MusicXML file to be similar to [repeat_example.musicxml.txt](https://github.com/mike-jshen/2311-Project/files/6196262/repeat_example.musicxml.txt)

**Actual:** The app did not show the “>> Conversion complete” message or produce any error message either. The app did not produce any output file and I was not able to download anything. 

**Priority:** High because implementing repeats is essential to convert most guitar tabs.

**Severity:** High. The scope of the course does cover repeat so you must be able to detect a repeated portion and produce appropriate tags. If not possible, an error message should be displayed. This bug affects the functionality of the code. Repeats are found in several tabs thus this is a bug that will be frequently encountered.

**Comment by aman9824** [comment]
Repeated tabs implemented and fixed
