### ISSUE TITLE
Grace Tag Not Generated

### ISSUE THREAD

**Issue by NiharikaRajnish** [mike-jshen/2311-Project#20]
ID #20
Who Raised: Nia Rajnish
Title: Grace Tag Not Generated
Version: Latest, Master branch
Platform: Mac OS, Eclipse, JavaSE-15
Reproduction: 
1. Run the project using the Gradle run 
2. Copy the following text tab into the text panel.

|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------g0h1----1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

[grace_note_example.txt](https://github.com/mike-jshen/2311-Project/files/6198845/grace_note_example.txt)

3. Clicked save and opened output .xml file.

Expected: The system should support grace notes. Any sequence of hammer-ons, pull-offs, or slides that are preceded by the character “g” should be treated as grace notes. Therefore the expected output should include a <grace/> tag between <note> and <pitch> for the 4th note(string 3, fret 0). 

Actual: The note attribute does not include a grace tag.

Priority: Since this is a system requirement it should be a high priority.

Severity: This bug does not stop or crash the conversion process so it is medium to low severity. 
Screenshots:

Expected:

<img width="862" alt="Screen Shot 2021-03-24 at 12 14 55 PM" src="https://user-images.githubusercontent.com/74378254/112344580-9c4bd600-8c9a-11eb-90c2-43d85ddb6c68.png">

Actual:
<img width="205" alt="Screen Shot 2021-03-24 at 12 16 46 PM" src="https://user-images.githubusercontent.com/74378254/112344683-b8e80e00-8c9a-11eb-8711-89c1539b7007.png">

**Comment by aman9824** [comment]
Grace Note working now
