### ISSUE TITLE
Does Not Support 2 Digit Numbers As One Note

### ISSUE THREAD

**Issue by NiharikaRajnish** [mike-jshen/2311-Project#21]
ID #21
Who Raised: Nia Rajnish
Title: Does Not Support 2 Digit Numbers As One Note.
Version: Latest version in master branch
Platform: Mac OS, Eclipse, JavaSE-15
Reproduction: 
1.Run the project using the Gradle run 
2. Copy the following text tab into the text panel.
[double_digit_note.txt](https://github.com/mike-jshen/2311-Project/files/6198934/double_digit_note.txt)
3. Clicked save and input the .xml file into https://opensheetmusicdisplay.github.io/demo/

Expected: There are 3 notes in this measure all on line 3. The last note is supposed to be played on fret 14. 

Actual: This system outputs a .xml file with 4 notes. The last note is separated into 2 individual notes one played on fret 1 and the other on fret 4. This is because the system does not recognize double-digit numbers as one-note and instead separates them.

Priority: A guitar has close to 24 frets and your system should be able to interpret these so this should be a high priority fix.

Severity: This bug does not stop or crash the conversion process so it is medium to high severity. 

Screenshots:
Expected:
<img width="304" alt="Screen Shot 2021-03-24 at 12 31 48 PM" src="https://user-images.githubusercontent.com/74378254/112347730-7e33a500-8c9d-11eb-81cc-cf461190deac.png">

Actual:
<img width="240" alt="Screen Shot 2021-03-24 at 12 36 33 PM" src="https://user-images.githubusercontent.com/74378254/112347758-85f34980-8c9d-11eb-9a30-8ba6bc73fe73.png">

**Comment by aman9824** [comment]
Two-Digit Implementation Fixed.
