### ISSUE TITLE
Does Not Support Repeat Measures

### ISSUE THREAD

**Issue by NiharikaRajnish** [mike-jshen/2311-Project#22]
ID#22

Who Raised: Nia Rajnish

Title: Does Not Support Repeat Measures

Version: Latest in master branch

Platform: Mac OS, Eclipse, JavaSE-15

Reproduction: 
1. Run the project using the Gradle run 
2. Copy the following text tab into the text panel.
[repeat_example.txt](https://github.com/mike-jshen/2311-Project/files/6199029/repeat_example.txt)
3. Clicked Convert.

Expected: I expected the “Conversion complete” text that usually indicates successful conversion. I also expect error messages giving the user a reason why certain conversions fail. 

Actual: This message was not displayed probably due to the inclusion of double vertical bars indicating repeats.

Priority: This is a system requirement therefore high priority.

Severity: This error stops conversion therefore high priority.

Screenshots:
Conversion does not complete, and no error messages to indicate what is wrong.

<img width="347" alt="Screen Shot 2021-03-24 at 12 47 26 PM" src="https://user-images.githubusercontent.com/74378254/112349369-0c5c5b00-8c9f-11eb-802b-360beed491c4.png">

**Comment by aman9824** [comment]
Repeated Measures working Now
