### ISSUE TITLE
Saving Empty XML

### ISSUE THREAD

**Issue by dokdek** [mike-jshen/2311-Project#23]
**Title:**
Saving Empty XML

**Reported By:**
Patchanon Suepai

**Version:**
Commit: 72ccfc9

**Platform:**
MacOS Catalina 10.15.7
Java 15
Eclipse 4.18

**Reproduction:**
Have no file converted, the program still lets you hit save and the save prompt will pop up, allowing the user to save. But when navigating to the file location, there is no file, not even an empty one.

**Expected:**

Either an error message should pop or an empty XML file should save.

**Actual:**

Nothing happens after hitting save.

**Priority:**
Low

**Severity:**
Low

**Screenshots:**

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/47761030/112374771-e2b02d80-8cb8-11eb-9108-ca2d149db761.png">

This is saving without converting

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47761030/112374878-02475600-8cb9-11eb-8233-1853ace2af5f.png">

This is the location where the file should have been saved, there is no "untitled.xml"

**Comment by aman9824** [comment]
Bug Fixed
