### ISSUE TITLE
XML Doesn't Change After Editing

### ISSUE THREAD

**Issue by dokdek** [mike-jshen/2311-Project#24]
**Title:**
XML Doesn't Change After Editing

**Reported By:**
Patchanon Suepai

**Version:**
Commit: 72ccfc9

**Platform:**
MacOS Catalina
Java 15
Eclipse 4.18

**Reproduction:**

|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

After importing a tab file, converting it, then editing the tab in the window, and hitting convert again. The changes wont be reflected on the new XML.

- Import a tab
- Convert that tab
- Edit the tab
- Convert again
- Save
- View XML
- Changes won't be viewed

https://www.soundslice.com/ XML reader.

**Expected:**

The edits will be reflected on the new XML

**Actual:**

The changes are not reflected, it reflects the original  XML

**Priority:**
Medium

**Severity:**
Medium

**Screenshots:**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47761030/112376841-55baa380-8cbb-11eb-8f2a-2b0c8d689e39.png">

This is the original tab that is inserted

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47761030/112376573-01afbf00-8cbb-11eb-9da0-f4a330df57bf.png">

This is the edited tab, it was just doubled.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47761030/112377201-d2e61880-8cbb-11eb-87a6-b5c96adf29c3.png">

This is the tab, it corresponds to the first tab inserted.

**Comment by aman9824** [comment]
Issue Fixed
