### ISSUE TITLE
Grace tag not created

### ISSUE THREAD

**Issue by gilmore35** [mike-jshen/2311-Project#25]
**ID# 25**

Who raised it: Abhirami Venugopal, abhirami@my.yorku.ca

Version: March 23,2021 version of software

Platform: Windows 10, Eclipse version 4.8.0, JavaSE-15

Reproduction: I uploaded this (guitar_grace), pressed “convert” and then clicked “save”.

Expected: I expected the output file to look similar to this(grace_note_example). Although it looked similar for the most part, no grace tag was created. 
![a](https://user-images.githubusercontent.com/77309918/112401075-18b4d800-8ce0-11eb-8c10-8e0164716b21.png)

Actual: A self-closing grace tag (<grace/>) should have been created inside the 4th note with step G and octave 3. The differences between expected and actual are highlighted in yellow. 

![a](https://user-images.githubusercontent.com/77309918/112401053-0fc40680-8ce0-11eb-9c69-911ecafa73c9.png)

Priority: Medium 

Severity: Medium. The scope of the course does cover grace notes so you must be able to detect a grace note and produce appropriate tags. However, Capricho Arabe does not contain any grace notes so you must be able to parse that without fixing this bug. Not all music tabs contain grace notes, so you might encounter this bug occasionally.

**Comment by aman9824** [comment]
Grace Note Fixed
