### ISSUE TITLE
Slide tag not created 

### ISSUE THREAD

**Issue by gilmore35** [mike-jshen/2311-Project#26]
ID# 26

Who raised it: Abhirami Venugopal, abhirami@my.yorku.ca

Version: March 23,2021 version of software

Platform: Windows 10, Eclipse version 4.8.0, JavaSE-15

MusicXML Viewer used: SoundSlice (https://www.soundslice.com/musicxml-viewer/)

Reproduction: 
1. Open application
2. Press "Add Song" and select [guitar_tab_slide.txt](https://github.com/mike-jshen/2311-Project/files/6201218/guitar_tab_slide.txt)
3. Press "Convert"
4. Press "Save"

Expected: I expected the output musicXML file to include a <slide> tag.

Actual: The output file generated did not include any <slide> tag. 

This is how your output looked like:

![a](https://user-images.githubusercontent.com/77309918/112401521-1737df80-8ce1-11eb-92a9-183a55f2348a.png)

A slide is a continuous line between 2 notes and defaults to a solid line in sheet music. No such line is found in the output created by the converter. 

Priority: High 

Severity: High. The scope of the course does cover slides so you must be able to detect slides and produce appropriate tags. This bug affects the functionality of the code. Slides are found in several tabs thus this is a bug that will be frequently encountered.  The right output after passing Capricho Arabe guitar tab as input will not be obtained as it contains slides.

**Comment by aman9824** [comment]
Issue Fixed
