### ISSUE TITLE
Editing does not save changes

### ISSUE THREAD

**Issue by tommylam16** [mike-jshen/2311-Project#27]
### ID
#27

### Who Raised
Tommy Lam

### Title
Editing does not save changes

### Version
`72ccfc9`

### Platform
Windows 10, Eclipse, JavaSE-15

### Production
1. Run application
2. Click "Launch Program"
3. Click "Add song"
4. Select [guitartabexample.txt](https://github.com/mike-jshen/2311-Project/files/6201517/guitartabexample.txt) in file directory
5. Select [guitartabexample.txt](https://github.com/mike-jshen/2311-Project/files/6201517/guitartabexample.txt) under "Added:"
6. Click "Convert"
7. Click "View"
8. Click "XML"
9. Save file
10.  Edit one of the notes by changing the number:
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----3-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

### Expected Result
The expected result should save the new changes

### Actual Result
 The actual result did not save the new changes

### Priority
Priority is High

### Severity
Severity is High because it does not save the changes made by the user, and there is no message to indicate that the save has been changed

### Screenshots

**Expected Result:**
![editted](https://user-images.githubusercontent.com/77315429/112407869-3177ba80-8ced-11eb-9f80-772f537954ef.PNG)

**Actual Result:**
![uneditted](https://user-images.githubusercontent.com/77315429/112407880-350b4180-8ced-11eb-8363-a3dfdb12899b.PNG)

**Comment by aman9824** [comment]
Thats, the feature we have, It is more robust, if you extra space or any other things, It will neglect it and work fine
