### ISSUE TITLE
Tabs with repeat does not output a new saved file

### ISSUE THREAD

**Issue by tommylam16** [mike-jshen/2311-Project#28]
### ID
#28

### Who Raised
Tommy Lam
### 
Title
Tabs with repeat does not output a new saved file

### Version
72ccfc9

### Platform
Windows 10, Eclipse, JavaSE-15

### Production
1. Run application
2. Click "Launch Program"
3. Click "Add song"
4. Select [guitarexample2.txt](https://github.com/mike-jshen/2311-Project/files/6201558/guitarexample2.txt) in file directory
5. Select [guitarexample2.txt](https://github.com/mike-jshen/2311-Project/files/6201558/guitarexample2.txt)  under "Added:"
6. Click "Convert"
7. Click "View"
8. Click "XML"
9. Save file

### Expected Result
The expected result should make a file of the XML and save it to the user's PC

### Actual Result
The actual result does not make a file of the XML and gives an error message

### Priority
Priority is High

### Severity
Severity is High because it does not allow the user to save the XML onto their PC
 
### Screenshots

**Actual Result:**
![image](https://user-images.githubusercontent.com/77315429/112408809-d34bd700-8cee-11eb-9bc7-443487d2c686.png)

**Comment by aman9824** [comment]
Repeated measures are implemented now. Bug Fixed
