### ISSUE TITLE
Grace note not supported

### ISSUE THREAD

**Issue by tommylam16** [mike-jshen/2311-Project#29]
### ID
#29

### Who Raised
Tommy Lam

### Title
Grace note not supported

### Version
72ccfc9

### Platform
Windows 10, Eclipse, JavaSE-15

### Production
1. Run application
2. Click "Launch Program"
3. Click "Add song"
4. Select [guitargracenote.txt](https://github.com/mike-jshen/2311-Project/files/6201609/guitargracenote.txt) in file directory
5. Select [guitargracenote.txt](https://github.com/mike-jshen/2311-Project/files/6201609/guitargracenote.txt) under "Added:"
6. Click "Convert"
7. Click "View"
8. Click "XML"
9. Save file

### Expected Result
The expected result should include the grace note in the XML

### Actual Result
The actual result does not include the grace note in the XML

### Priority
Priority is High

### Severity
Severity is High because it is part of the System's Requirement

### Screenshots

**Actual Result**
![uneditted](https://user-images.githubusercontent.com/77315429/112409951-c16b3380-8cf0-11eb-81db-5dc5568ca33f.PNG)

**Expected Result**
![grace note](https://user-images.githubusercontent.com/77315429/112410070-fc6d6700-8cf0-11eb-9fdf-96147e01d812.PNG)

**Comment by aman9824** [comment]
Grace Notes Implemented. Bug Fixed.
