### ISSUE TITLE
Failed to convert song

### ISSUE THREAD

**Issue by Madison-Hartley** [mike-jshen/2311-Project#30]
Title:
Failed to convert song

Reported By:
Madison hartley

Version:
Commit: 72ccfc9

Platform:
Windows 10
Java 15
Eclipse 4.18

Reproduction:
Start the software, go to conversion screen, select the attached text file
[AllAlongTheWatchtower.txt](https://github.com/mike-jshen/2311-Project/files/6201661/AllAlongTheWatchtower.txt)
and then convert. Save, then open xml file. 

Expected:

An error message for the failure, or, a converted song.

Actual:

The output is as follows:
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1"><part-list><score-part id="P1"><part-name>Classical Guitar</part-name></score-part></part-list><part id="P1"/></score-partwise>
It is very incomplete.

Priority:
Medium

Severity:
Low

Screenshots:
![hhhh](https://user-images.githubusercontent.com/46429357/112410886-53277080-8cf2-11eb-8403-6d36ed17dc46.PNG)

**Comment by aman9824** [comment]
Issue Fixed
