### ISSUE TITLE
Cannot View Text File

### ISSUE THREAD

**Issue by Madison-Hartley** [mike-jshen/2311-Project#31]
Title:
Cannot View Test File

Reported By:
Madison hartley

Version:
Commit: 72ccfc9

Platform:
Windows 10
Java 15
Eclipse 4.18

Reproduction:
Start the software, go to conversion screen, select the attached text file
[drumTestTab.txt](https://github.com/mike-jshen/2311-Project/files/6201689/drumTestTab.txt)

and then select "view".

Expected:

The inputted file's contents.

Actual:

Nothing appears, nothing pops up, nothing happens.

Priority:
Low

Severity:
Low

Screenshots:
![fghhf](https://user-images.githubusercontent.com/46429357/112411118-baddbb80-8cf2-11eb-8cec-792161a20fb3.PNG)

**Comment by aman9824** [comment]
Sir, According to the steps, you have to select the file which you want to view in Added section and then click on View button for viewing the content.
