### ISSUE TITLE
Drum Tab Not Converting

### ISSUE THREAD

**Issue by Madison-Hartley** [mike-jshen/2311-Project#32]
Title:
Drum Tab Not Converting

Reported By:
Madison hartley

Version:
Commit: 72ccfc9

Platform:
Windows 10
Java 15
Eclipse 4.18

Reproduction:
Start the software, go to conversion screen, select the attached text file
drumTestTab.txt

and then select "convert", and then save the file to desired location. Open the file.

Expected:

Either an error message, or a drum xml file.

Actual:

This output, which is incomplete and for guitar.
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1"><part-list><score-part id="P1"><part-name>Classical Guitar</part-name></score-part></part-list><part id="P1"/></score-partwise>

Priority:
Medium

Severity:
Low

Screenshots:

![dh](https://user-images.githubusercontent.com/46429357/112411442-4ce5c400-8cf3-11eb-8612-71f5bddd6129.PNG)

**Comment by aman9824** [comment]
Issue Fixed
