### ISSUE TITLE
Error prompt issue

### ISSUE THREAD

**Issue by suhasid098** [mike-jshen/2311-Project#33]
Title:
Error prompt issue

Author:
Suha Siddiqui

Version:
Commit: 72ccfc9

Platform:
Windows 10
Java 15
Version: 2020-12 (4.18.0)

Reproduction:

Based on the user manual the following tab was entered into the content window:

|-15--------|
|-5--------|
|-5--------|
|-5--------|
|-15--------|
|-5--------|

Then the convert and save button were pressed for the file to be dragged and dropped into https://opensheetmusicdisplay.github.io/demo/.

Expected:

The program would prompt the user for an error regarding the uneven measure duration.

Actual:

The program allowed the user to proceed to save the file into the desktop, leading the final file saved to be faulty. Not allowing the user to successfully view the content in the saved file through https://opensheetmusicdisplay.github.io/demo/
![Capture](https://user-images.githubusercontent.com/77293073/112413941-87516000-8cf7-11eb-8478-ec26327f6028.PNG)

Priority:
Low

Severity:
Medium

**Comment by aman9824** [comment]
Thats, the feature we have, It is more robust, if you extra space or any other things, It will neglect it and work fine
