### ISSUE TITLE
Fret entry issue

### ISSUE THREAD

**Issue by suhasid098** [mike-jshen/2311-Project#34]
Title:
Fret entry issue
Author:
Suha Siddiqui

Version:
Commit: 72ccfc9

Platform:
Windows 10
Java 15
Version: 2020-12 (4.18.0)

Reproduction:

Based on the user manual the following tab was entered into the content window:

|-10-------|
|-5--------|
|-5--------|
|-5--------|
|-10-------|
|-5--------|

Then the convert and save button were pressed for the file to be dragged and dropped into https://opensheetmusicdisplay.github.io/demo/.

Expected:

The program should output the double-digit note into the appropriate string  

Actual:

The program outputs the double-digit fret as separate values. For example, if the fret value 10 was entered into string 'e', it will separate the 1 and 0.
![image](https://user-images.githubusercontent.com/77293073/112414288-33934680-8cf8-11eb-8686-0096c0af2d8f.png)

![image](https://user-images.githubusercontent.com/77293073/112414425-66d5d580-8cf8-11eb-8734-702b8b6e0c3d.png)

Priority:
High

Severity:
High

**Comment by HappyNimbus** [comment]
Double digits are now added and it should work properly.
