### ISSUE TITLE
Repeats issue

### ISSUE THREAD

**Issue by suhasid098** [mike-jshen/2311-Project#35]
Title:
Repeats issue
Author:
Suha Siddiqui

Version:
Commit: 72ccfc9

Platform:
Windows 10
Java 15
Version: 2020-12 (4.18.0)

Reproduction:

Based on the user manual the following tab was entered into the content window:

|-----------0-----||----------0--------4|
|---------0---0---||----------0--------||
|-------1-------1-||\*---------1-------\*||
|-----2-----------||\*---------2-------\*||
|---2-------------||------2---2--------||
|-0---------------||--0-------0--------||

Then the convert and save button were pressed for the file to be dragged and dropped into https://opensheetmusicdisplay.github.io/demo/.

Expected:

The program should printout a tab that displays the repeats at the end of the bar for the indicated section above. 

Actual:

The program doesn't allow for conversion for the given tab when the "convert" button is pressed as the file does not generate content when the "save" button is pressed and the message for successful conversion does not appear.

![image](https://user-images.githubusercontent.com/77293073/112415198-ced8eb80-8cf9-11eb-85b0-7f9ea7925901.png)

Priority:
High

Severity:
High

**Comment by aman9824** [comment]
Repeated Tabs fixed
